version: 2

updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "team-leads"
    assignees:
      - "dev-team"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore major version updates for Next.js to avoid breaking changes
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
    auto-merge:
      security-updates: true

  # Enable version updates for pip
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "team-leads"
    assignees:
      - "dev-team"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    auto-merge:
      security-updates: true
